### ISSUE TITLE
执行程序问题

### ISSUE THREAD

**Issue by zhoukaiwei66** [liushulinle/PLOME#24]
您好，我在执行您的程序的时候遇到了
Traceback (most recent call last):
  File "G:/PLOME-main/finetune_src/train_eval_tagging.py", line 268, in <module>
    print('\tsk_or_py=', FLAGS.sk_or_py)
  File "G:/PLOME-main/finetune_src/train_eval_tagging.py", line 203, in train
    start_time = time.time()
  File "G:\PLOME-main\venv\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "G:\PLOME-main\venv\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "G:\PLOME-main\venv\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "G:\PLOME-main\venv\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Key: stroke_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_475]]
  (1) Invalid argument: Key: stroke_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.
请问这个问题您有解决方案么，本地环境和您在readme里面说的一样，谢谢您

**Comment by TommyTang930** [comment]
错误显示“Invalid argument”，是不是传参有问题？我用作者的代码，进行微调是没有问题的，能够抛出evaluation的结果。

**Comment by zhoukaiwei66** [comment]
> > 您好，我在执行您的程序的时候遇到了 Traceback (most recent call last): File "G:/PLOME-main/finetune_src/train_eval_tagging.py", line 268, in print('\tsk_or_py=', FLAGS.sk_or_py) File "G:/PLOME-main/finetune_src/train_eval_tagging.py", line 203, in train start_time = time.time() File "G:\PLOME-main\venv\lib\site-packages\tensorflow\python\client\session.py", line 950, in run run_metadata_ptr) File "G:\PLOME-main\venv\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run feed_dict_tensor, options, run_metadata) File "G:\PLOME-main\venv\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run run_metadata) File "G:\PLOME-main\venv\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call raise type(e)(node_def, op, message) tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found. (0) Invalid argument: Key: stroke_ids. Can't parse serialized Example. [[{{node ParseSingleExample/ParseSingleExample}}]] [[IteratorGetNext]] [[IteratorGetNext/_475]] (1) Invalid argument: Key: stroke_ids. Can't parse serialized Example. [[{{node ParseSingleExample/ParseSingleExample}}]] [[IteratorGetNext]] 0 successful operations. 0 derived errors ignored. 请问这个问题您有解决方案么，本地环境和您在readme里面说的一样，谢谢您
> 
> 错误显示“Invalid argument”，是不是传参有问题？我用作者的代码，进行微调是没有问题的，能够跑出evaluation的结果

参数都没变，就是作者那个start.sh，我看网上有说是本地的cuda和 tensorflow的环境问题，我用的cuda10.0 cudnn7.4 tensorflow1.14,我也看不出来哪里出了问题

**Comment by TommyTang930** [comment]
> > > 您好，我在执行您的程序的时候遇到了 Traceback (most recent call last): File "G:/PLOME-main/finetune_src/train_eval_tagging.py", line 268, in print('\tsk_or_py=', FLAGS.sk_or_py) File "G:/PLOME-main/finetune_src/train_eval_tagging.py", line 203, in train start_time = time.time() File "G:\PLOME-main\venv\lib\site-packages\tensorflow\python\client\session.py", line 950, in run run_metadata_ptr) File "G:\PLOME-main\venv\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run feed_dict_tensor, options, run_metadata) File "G:\PLOME-main\venv\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run run_metadata) File "G:\PLOME-main\venv\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call raise type(e)(node_def, op, message) tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found. (0) Invalid argument: Key: stroke_ids. Can't parse serialized Example. [[{{node ParseSingleExample/ParseSingleExample}}]] [[IteratorGetNext]] [[IteratorGetNext/_475]] (1) Invalid argument: Key: stroke_ids. Can't parse serialized Example. [[{{node ParseSingleExample/ParseSingleExample}}]] [[IteratorGetNext]] 0 successful operations. 0 derived errors ignored. 请问这个问题您有解决方案么，本地环境和您在readme里面说的一样，谢谢您
> > 
> > 
> > 错误显示“Invalid argument”，是不是传参有问题？我用作者的代码，进行微调是没有问题的，能够跑出evaluation的结果
> 
> 参数都没变，就是作者那个start.sh，我看网上有说是本地的cuda和 tensorflow的环境问题，我用的cuda10.0 cudnn7.4 tensorflow1.14,我也看不出来哪里出了问题

我这边是：
① CUDA Version : 10.2
② Driver Version: 440.118.02
③ tensorflow-gpu: 1.12.0
